[Service]
WorkingDirectory=/opt/smart-fire-detection-v2
Environment=PYTHONPATH=/opt/smart-fire-detection-v2

ExecStart=
ExecStart=/opt/smart-fire-detection-v2/venv/bin/python -m manager.calibration_worker
